<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Accordion:
            orientation: 'vertical'

            AccordionItem:
				title: "Panel 2"
				Label:
					text: "Panel 2 Text"
					font_size: 32


            AccordionItem:
                title:'panel 2'

                Label:
                    text:'panel 2 text'
                    font_size: 32
