
<MyLayout>
    BoxLayout:
        orientation: 'vertical'
        size: root.width, root.height

        Carousel:
            direction:'right'
            Label:
                text:'label 1'
            Label:
                text:'label 2'
            Label:
                text:'label 3'
            AsyncImage:
                source:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Image_created_with_a_mobile_phone.png/330px-Image_created_with_a_mobile_phone.png'
